### ISSUE TITLE
Missing changelogs

### ISSUE THREAD

**Issue by maelchiotti** [flutter-cavalry/saf_util#1]
Hi, I noticed that the changelogs are missing for several versions, including the latest ones, for this package but also saf_stream.

I believe they are pretty import to let us know of what was improved or changed, so I'm requesting that you update them when you find the time!

In any case, I'm happily updating my app in production with those great packages 🚀

**Comment by mgenware** [comment]
Hi, unmentioned releases are mostly pre-1.0 minor documentation / example updates. But yeah, these are solid suggestions! As this package is starting to get some adoption, we should definitely document every changes from now. Closing as fixed.
