### ISSUE TITLE
 Reduce minimum required dart version

### ISSUE THREAD

**Issue by Chiggy-Playz** [flutter-cavalry/saf_util#2]
The package current needs flutter dart sdk version to be >=3.5.3 which is latest at the moment of writing, but the plugin doesn't use any dart or flutter feature that it needs 3.5.3 as the minimum version. Can it be lowered so we can use it in our project?

Here's the result of `flutter pub get`:
```
Resolving dependencies... 
The current Dart SDK version is 3.5.1.

Because mime_flutter depends on saf_util >=0.0.2 which requires SDK version >=3.5.3 <4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.24.3. 
```

And flutter version
```
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (8 weeks ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2
```

**Comment by mgenware** [comment]
@Chiggy-Playz Makes sense! Didn't know newly created Flutter project has this aggressive min SDK version settings. Published v0.4.0 with relaxed min Dart and Flutter settings.
